### PR TITLE
update for latest selenium

### PR DESCRIPTION
**Pull request by PaleNeutron**
[find_element_by_id](https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el) type methods are removed from `selenium` science version `4.30`

### CODE REVIEW

**Comment by andyreagan** [comment]
@jakevdp what is needed to merge in these updates? if there are tests or other things that are needed I'd be happy to help.

**Comment by rencryptofish** [comment]
hi @jakevdp, do you happen to know if we can merge this in, tested locally seems fine and minor fix

**Comment by normanrz** [comment]
It would be fantastic to get this merged 🚀

**Comment by fleimgruber** [comment]
@PaleNeutron Just curious, are there plans to support selenium >=4.30 or is this done in another PR?

**Comment by fleimgruber** [comment]
I see, thanks for the heads up and the link!

**Pull request closed without merging**
