### PR TITLE
allow Paths in save()

### PR DESCRIPTION
**Pull request by RoyalTS**
Complement to https://github.com/altair-viz/altair/pull/2355

### CODE REVIEW

**Comment by RoyalTS** [comment]
Not quite sure where the test failures are coming from. They seem unrelated to the changes I made

**Comment by jakevdp** [comment]
Looks good! We'll need some tests of this here as well. I think you could add one of path-based format inference here: https://github.com/altair-viz/altair_saver/blob/e710a767f3f6210a4026628936c000dc3e8d8e19/altair_saver/tests/test_core.py#L309-L315

and add one of file opening and writing here: https://github.com/altair-viz/altair_saver/blob/46cdbff06e6222bfdd045bda82951cb119572228/altair_saver/tests/test_utils.py#L63-L72

As a side-note, it looks like we don't have any integration tests of saving a chart to a disk. That is indirectly covered by unit tests of the relevant utilities, but since saving a chart is a core functionality of this library, it would be better to have a full end-to-end test of that behavior!

**Comment by RoyalTS** [comment]
> We'll need some tests of this here as well. I think you could add one of path-based format inference here:

Wouldn't https://github.com/altair-viz/altair_saver/blob/46cdbff06e6222bfdd045bda82951cb119572228/altair_saver/tests/test_utils.py#L34 be the better place for testing format inference from the passed `fp`?

If so, I'm not sure I understand the current test. The `use_filename==False` mode just seems like a more convoluted way of generating a filename, one that introduces a failure mode (the temp file not being created) that has nothing to do with the test. What am I missing?

**Comment by jakevdp** [comment]
The test aims to exercise format inference from either a file pointer (in which case `fp.name` is the relevant name) or a filename (in which the string itself is the relevant name). I'm not certain I understand what failure mode you're referring to.

**Comment by RoyalTS** [comment]
Oh, I see. In that case one would want to test four different possible values for `fp`?
1. string path
1. pathlib.Path
1. file pointer
1. output streams

with format inference working as inteded for 1-3 and failing in the fourth case?

**Comment by jakevdp** [comment]
Yeah, that sounds right.

**Comment by jakevdp** [comment]
New tests look great!

**Comment by RoyalTS** [comment]
The build seems to have encountered an internal error. Any way to trigger a new one manually?

**Comment by jakevdp** [comment]
I triggered a new run

**Comment by RoyalTS** [comment]
Lots of failing tests but none look like they're due to the changes?

**Comment by jakevdp** [comment]
Yeah, looks like there are failures on master due to tests not being resilient to dependency updates.

**Comment by jakevdp** [comment]
Also the lint job is just failing for reasons I don't understand.

**Comment by RoyalTS** [comment]
That makes two of us then :)

**Comment by joelostblom** [comment]
Thanks for you PR @RoyalTS . As you have noticed, there hasn't been any development in this repo for a while. Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.

**Pull request closed without merging**
