### PR TITLE
BUG: make selenium saver respect chart theme

### LINKED ISSUE #21: Chart.save produces different colors between html, png, and svg, not using enabled theme
Hello, I'm using altair 4.0.1 and produce a chart using 
`alt.themes.enable('fivethirtyeight')`

When I use chart.save('foo.html') it uses the colors and layout from the theme that looks something like this (cropped oddly due to data sensitivity)

image

But when I use chart.save('foo.png') or chart.save('foo.svg'), the colors and layout are from the default theme
image

I tried looking in the docs for [changing the theme](https://altair-viz.github.io/user_guide/configuration.html?highlight=theme#changing-the-theme) on a chart and for [save](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html?highlight=save#altair.Chart.save) and couldn't find how to specify the theme when saving pngs and svgs.

### PR DESCRIPTION
**Pull request by jakevdp**
Partially fixes #21

### CODE REVIEW

**Comment by jakevdp** [comment]
I still would like to figure out how to make the ``.vg.json`` save path reflect the theme.

**Comment by Amarounek** [comment]
Well, I can also show the difference between figure save it "manually" and by **saver**. I think that such a huge difference is unintended. Should I open new issue topic for it?

**Comment by jakevdp** [comment]
Sure, open an issue and show the difference. Note that the nodejs-based savers do not support themes, even after this PR is merged, and there does not appear to be any way to fix that issue at the moment due to a limitation in vega-cli.

**Comment by jakevdp** [comment]
I'm going to merge this – it appears to correct the theme issue for selenium + png & svg.

**Pull request merged**
